### ISSUE TITLE
Enable Reverse Proxy and On Setup generate client keys

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#11392]
The entire configuration could be made VASTLY more simple, especially for environments like kubernetes etc. if we could simply have RavenDb recognize that it is actually running in https by having it recognize reverse proxy headers being passed in (asp.net core allows this in your startup.cs) and then have it simply be open or use a temporary admin password you set in the config for the first load to gain access.  

Then once you're in, you can generate client certificates directly in the UI.

The current approach is WAY too complex and prone to errors. I need to configure this on 3 test environments and it's just a massive PITA as it stands right now.

**Comment by iftahbe** [comment]
Maybe I'm missing something here but I don't understand how that will simplify things.
If I understand correctly, you had problems generating and using a server certificate.
How would a password (to grant easier first access?) solve the problem that you need to start RavenDB with a server certificate?

The server must run with a server certificate. To gain first access, you can use the server certificate (acting as a client certificate).
Then, afterwards, client certificates can be generated in the UI.

Think about the server certificate as a password. It can also be expressed as a base64 string that you can pass along to the client on first access.

**Comment by JohnGalt1717** [comment]
1. If RavenDb is behind a reverse proxy then I shouldn't need a server certificate in RavenDb at all. It's done for me, RavenDb should be listening on http ONLY and using the reverse proxy information to know it's in SSL at the ingress automatically (Posted previously in the other ticket)

2. Since it's behind a reverse proxy and it can communicate directly with it's cluster nodes insecure in kubernetes because there is no way for external traffic to monitor the kubernetes cluster, there is no reason at all in this configuration to require ANY server side certificates and ravendb should know this.

3. I should still however require clients to use their certificate (or a boring old login and complex password which wouldn't be any less secure) even though the server itself is setup to recognize the reverse proxy configuration and know it's secure so I shouldn't be able to login client certificate-less.

As far as I'm aware as soon as you enable insecure mode, for the server itself it also doesn't require client certs.

**Comment by JohnGalt1717** [comment]
To elaborate on #2, basically to really work in an isolated environment like k8s, docker-compose etc, there needs to be 2 separate mechanisms:

Studio needs to use l/p. Browser certificates aren't going to happen because ingress client certificates is global to the entire ingress not just your ravendb endpoints defined. Thus studio needs different auth, and then client certificates are fine internally, but really not optimal. A single solution would be better.

**Comment by ayende** [comment]
1) The problem is that it won't be able to do _authentication_. How would we be able to tell what permissions to give to the request?
2) In general, TLS termination is a bad idea, because in the portion of the network where the data goes in plain text is vulnerable to a lot of mischief. In particular, if you have other actors on the K8s running.
When running in K8s, it is fairly common to have some apps running inside K8s as well as well as access RavenDB from outside. In that case, you cannot run it without authorization.
3) That would mean that you have to do some non trivial configuration on the reverse proxy to do SSL client cert auth, then send the values to RavenDB.
Of course, we'll have to guard against direct access that will provide those headers, etc. 

RavenDB security is a binary property, intentionally. Complex configuration (run https locally, auth based on headers, coordinate with reverse proxy, etc) is not simple. 
You can define K8s to avoid TLS termination and send the request directly to RavenDB. In that case, everything works as it should and there is no need for this complex setup.

Login & password mode over plain text isn't safe.

**Comment by JohnGalt1717** [comment]
I've spoken at length with a friend of mine that gives lectures at Kubernetes conferences at the behest of both Google and Oracle. I think that there is a major misunderstanding of how K8s is designed to be used.

1. K8s is designed to be used with ingress that that terminates SSL. It is not designed to pass through SSL to services. It's a hack enabled by the underlying services (HA proxy etc.) that it allows this, not the design intent.  K8s to quote him and their documentation, is designed to be a secure, reproducible environment to the edge and should be treated no different than bare iron running on a rack with a router, firewall and reverse proxy of the past.

2. TLS termination is not a bad idea if setup correctly within your k8s environment. Your argument is "because you might have stuff running in k8s that is dangerous, it's dangerous to do it all the time.  That's the problem, your K8s environment is supposed to be a microcosm of exactly what your system needs and nothing else and shouldn't have any direct access to anything incoming at all with the exception of your ingress controller. And if you have malicious stuff that is stealing data by packet sniffing (not really possible because the containers don't have network snoop access unless you explicitly give them it with NET_CAP) and then using egress to send that to a 3rd party externally, you've got MUCH bigger problems that a client certificate and TLS isn't going to solve.

3. Login and password is only dangerous if done across a network for which you don't have complete control that is also unencrypted. By definition on k8s you have 100% control, no different than an isolated rack behind a RP in the past of the internal non-routable network.  All traffic that goes across a network that you don't have complete control MUST be encrypted, and in that environment, login and password is no less secure than a client certificate. In fact, alone, login and password is identical to a client certificate because both are bearer token, nothing more and don't validate anything other than possession.  Thus an RP that handles SSL offload that then sends decrypted communication across the non-routable, closed network with containers that cannot packet sniff and services that are directly communicating across that non-routable network without the ability to packet sniff is NOT a security risk. This is the fundamental design principle of k8s.  Yes you can defeat it.  But you have to work hard to do so, and that's your problem and we shouldn't be designing things to defeat stupid network admins.

A correct design of a k8s cluster will always and should always look similar to:

1. Ingress controller that has VERY limited ports accessible. Typically only 80 and 443. In fact one of the limiting factors of k8s right now is that it is only designed to ingress http traffic.  This is by definition a reverse proxy.

2. One or more apis/micro services receiving traffic redirected and decrypted by the ingress controller configured a services behind the ingress controller that specifically map ports and other required configuration to the pods within those scale sets or deployments. A database should never be receiving direct requests across the ingress controller if done correctly.

3. The apis/microservices SHALL not receive traffic directly, and SHOULD only communicate with other things WITHIN the kubernetes cluster. I..e the apis/microservices should be talking directly over the k8s internal, non-routable network to databases ALSO hosted within the kubernetes cluster, they should NEVER be communicating over routable addresses to services within the k8s cluster. (which is how your documentation is designed)

4. Your cluster SHOULD contain all services necessary for your environment to be fully functional. I.e., while it's common practice for your cluster to be talking to other cloud services (i.e. Azure Media Services or similar), all of those services should be within the k8s cluster whenever possible and SHOULD NOT be publicly accessible. And if you do need external services, there are only 2 ways that you can communicate with them: 1. Initiate the communication via egress, 2. have them communicate via the ingress controller reverse proxy to a service.

5. A properly configured k8s environment with the database hosted withink the k8s cluster SHOULD NOT have the database directly accessiable over the ingress controller. In fact, RavenDb should not have ANY services setup nor ingress definitions at all for anything other than Raven Studio, and even that should be restricted by IP address at the ingress controller if possible and simply disabled when not in active use outside the k8s cluster.) 

6. There currently is no way with how RavenDb is setup to have RavenDb properly hosted within a cluster with websites. Why? Because SSL pass through is a global ingress setting.  Hence you would have to enable it on all your micro services and websites within the k8s cluster.  That means you have to maintain that certificate on ALL of them instead of just the ingress controller where it should occur. Further RavenDb doesn't support key/crt thus you cannot automate this with cert-manager or any mass change of the certificate that is supported by k8s either so even if this was desirable (it is not by any stretch in any configuration) it's a non-starter.

All of this is stated within the k8s documentation AND supported by experts from google and oracle on the topic.

Thus a correct use of RavenDB in an ideal environment would be RavenDb within the k8s environment WITHOUT any access at all externally EXCEPT basic management tasks within Raven Studio.

The way that you have your documentation and the design considers only RavenDB being hosted in K8s in a 0 trust environment for public consumption and even then you're defeating the ingress design principles of k8s.  It does not address, nor does it appear that the ravendb model for access is even capable of properly handling a real-world, best practices implementation of k8s where all services that will talk to the ravendb itself are internal to the k8s cluster and ONLY basic management will be done over the wire.

I strongly encourage you to rethink this so that it can be properly configured to support k8s as intended to be used as this is a fundamental design pattern that has enormous uptake.

As an aside, rvn cli (rvn is there but not marked executable and even marking it executable doesn't appear to allow it to run) doesn't work within the docker container so you cannot connect to your k8s cluster, exec into the pods and do things using the Raven CLI as it currently stands which defeats how Raven should be setup in a closed environment because we can't script creation of databases etc. using the cli on deploy.

If you're interested, what I would suggest you strongly consider doing is:

1. Decouple client certificates from server certificates. The 2 shouldn't have anything to do with each other, and the first client certificate should be generated on first run and all subsequent access to the actual database (not necessarily raven studio) should require that client certificate or another created one.
2. Enable Studio to recognize reverse proxies. In the setup wizard or on the screen if you really have an issue with this, make a note that it's running behind an RP if you wish but with encryption to the RP so that people KNOW that they're making that choice and should have their network configured correctly. (and reject if no server certificate AND no RP with encryption)
3. Allow login and password for management functionality over raven studio and allow us to disable from the cli within the containers the raven studio.  Only enable l/p functionality if TLS either directly or via RP if you wish.
4. Completely decouple raven studio from the ravendb containers so that a cluster can have a single container of raven studio that can be controlled as up or down from kubectl and thus control availability at all, and then have separate containers for ravendb itself that is completely headless.
5. I'd suggest that Raven Studio etc. automatically should create a self-signed server certificate on first run if one isn't defined in configuration and allow it to be overridden in the setup wizard if so desired by the end user so that HTTPS is always available, and the end user can choose to trust the self-signed cert or not as a fall back if not behind an RP (this would also allow the RP to send reencrypted to ravendb within the cluster if you insist using the self-signed cert which still terminating the public certificate)


This could be accomplished incrementally by not throwing an error on startup if ServerURL and ServerPublicUrl don't have the same scheme and then enforcing the scheme of ServerPublicUrl against ServerURL for incoming requests using the Reverse Proxy configurations in Kestrel.  Then add login/password support for Raven Studio, then split studio into it's own container that manages one or more nodes of RavenDb containers but does so only on the non-routable k8s network.

Almost all of this is possible right now but it has major blockers that prevents best practices k8s deploy. I.e. I can set an enviornment variable of RAVEN_Security_UnsecuredAccessAllowed and value of PrivateNetwork.  This will enable the microservices within k8s to communicate without encryption and thus eliminate the overhead within the non-routable network.  (and even using a cert in this environment that was decoupled from the server cert for identification would possibly be desirable) That's great and I would then just not expose TCP over the ingress nor services.  The problem becomes Raven Studio which is a major blocker for management as it currently stands across a properly configured k8s cluster with reverse proxy doing what it should.

**Comment by ayende** [comment]
1) Your situation is a scenario where your K8s is running in a trusted envrionment. 
We don't consider this to be a valid scenario. I wrote about this here:
https://ravendb.net/articles/the-network-is-always-hostile

Microsoft leaked access to 250 *million* support records because of this (false) assumption.
See: https://www.comparitech.com/blog/information-security/microsoft-customer-service-data-leak/

Another important reading on the topic: https://blog.cryptographyengineering.com/2015/08/16/the-network-is-hostile/

2) Assume that you a running a node application in a container. You are using a dependency that opens a shell:
https://www.zdnet.com/article/three-npm-packages-found-opening-shells-on-linux-windows-systems/

Now you effectively have an instance in your system that is owned by a malicious user. 
Your security model at this points assume that you cannot escape the limits of the container at this point.

For example:
https://blog.trailofbits.com/2019/07/19/understanding-docker-container-escapes/

At this point, you are now with a malicious agent on the system and they can listen to everything.

We take the stance of defence in depth, since there is little cost of doing TLS to RavenDB and many benefits.

3) You assume that everything is fine, and that there have been no issues / vulnerabiltiies. If you have any issue, your
option leads to catastorphic data loss. If we are running encrypted, you have many walls yet to climb.

A client certifcate is signifncantly better than a bearer token. You cannot MITM with a client certificate, even if you have root CA 
installed, for example. You cannot reply requests and operations with client certificate. 
The idea is that with cleitn certificate, both sides will authenticate properly using cryptographic primitives. That is *significantly*
stronger gurantees than bearer tokens or login/pass.


With regards to the K8s setup, you can define the following.
* SSL passthrough to the RavenDB instances.
* Limit access to the nodes based on IP.

Alternatively, don't expose RavenDB to the external world at all, just use internal DNS and use TLS inside the K8s network.

The rvn exec should be marked as executable, and should just work inside a container. Can you create a separate issue on this?


1) The server certificate is used to authenticate to _other_ ravendb instances as a client certificate, as well as possiblity for server authentication,
but not beyond that.

The model you suggest in this case would result in a much more complex setup process, because you have to create multiple certificates.

2 & 3) No, doesn't meet our security modeling requirements.

4) I don't think that I follow what you mean here?
The studio is not actually related to anything. This is just the web interface for a node.
You can do the same using REST operations in the same manner.
You can deploy RavenDB without the studio, if you so wish.

5) Self signed certificates are *problematic*. They won't work by default with most clients.
For example, you'll have to go through a process of trusting the certificate when working from your own dev machine. 
That is complex, prune to failure and causes support issues.

We use Let's Encrypt by default preciesely because in the end things Just Work.

**Comment by JohnGalt1717** [comment]
As I've said, the issue isn't certificates, it's how you're going about doing them.  If you believe all of the above, all of which can be easily mitigated, then you still need to be using a valid SERVER certificate. Your Let's Encrypt implementation CANNOT be used in k8s.  A properly configured k8s implementation uses Reverse proxy and cert-manager. 

Thus:

1. RavenDb needs to work in this environment. If you want it to have server side encryption, that's fine, let us mount the cert-manager secrets and it should just work and then I'll set our reverse proxy to encrypt to the service as well, you're done. That means directly support monitoring crt/key files and using those instead of the windows-centric pfx standard.

2. RavenDb cannot be publicly accessible in a properly configured k8s environment because of the use of client certificates for Raven Studio. (client certificates are fine for the other containers within the k8s cluster talking to RavenDb, it isn't fine for a properly configured environment with a single source of SSL termination (and then reencryption if you believe it's required using self-signed certs that don't expire)) This needs to be addressed so that Raven Studio can be accessed through the reverse proxy. That means Raven Studio needs to be reverse proxy aware and support login and password over the encrypted channel. (and I would completely disable public access to anything else and Raven Studio shouldn't be communicating directly either via ajax)

3. RavenDb needs to allow all the nodes in the cluster to work directly across the private network in k8s, not against publicly addressable dns entries and ONLY expose Studio against the RP.


What I've done temporarily is use openssl in the exec to convert the key/crt files into pfx (not ideal) and then use that with Raven and then tell it that it's public addresses are all internal dns to the cluster and then use kubectl port forwarding to access Raven Studio.  This works for 90 days and then has to be redone. And it's a pita to use.

Obviously this is a hack required because of a design that doesn't take into account k8s properly configured as a single environment for your entire solution as I've previously outlined because of assumptions of RavenDb being publicly accessible outside the k8s cluster which is not how it will be used in the real world by the vast majority of people properly using k8s.

(BTW, your docker container release example requires --privilaged which no container should be run as, and can't get those permissions itself unless a human maliciously runs it that way short of a massive security breach in K8s itself, which of course, will directly expose your storage and everything else including your server certificate and thus allow decoding of all of the data across the wire and at rest anyhow.)

**Comment by JohnGalt1717** [comment]
I take it back. Using port forwarding in Kubernetes, UnsecureAccessAllowed doesn't work even if set to PublicNetwork

**Comment by ayende** [comment]
Not sure why you believe that Let's Encrypt cannot be used in K8s, we have done 
so in quite a few cases, with no issues.

1) To integrate with K8s certificates, the Security.Certificate.Exec gives you the ability
to fetch the certificate via K8s' mechanisms.

2) RavenDB is design so it would do its SSL termination and authentication. I understand that you may 
not like this behavior, but I have no plans on changing it, for the reasons specified in the issue. 
The term "easily mitigated" is another form of saying "potential data leak". If your security system assumes that
everything has been properly setup, you're at risk. RavenDB's security design takes the assumption that the network
is hostile, always. Because a single breech can be catastrophic.

3) That is possible, yes. You can setup: `PublicServerUrl.Tcp.Cluster`.
See: 
https://github.com/ravendb/ravendb/blob/v5.0/src/Raven.Server/Config/Categories/CoreConfiguration.cs#L27

This is designed for just this scenario, so the inter cluster communication will go through private IPs instead
of the public ones.

Your OpenSSL work can be done in a script and then provided to Security.Certificate.Exec, and at this point, RavenDB 
will take care of that.

As for Dokcer and privilaged, can you explain what you mean?
We don't require this to run.

I checked:
https://ravendb.net/docs/article-page/4.2/csharp/start/installation/running-in-docker-container
https://github.com/ravendb/ravendb/blob/v5.0/docker/readme.md
https://hub.docker.com/r/ravendb/ravendb/

I'm not sure where you got that, and I would like to fix it.

**Comment by JohnGalt1717** [comment]
You can EITHER run Let's encrypt with cert-manager as designed an intended by k8s, OR you can run it for RavenDb.  You can EITHER run k8s with Reverse Proxy ingress as intended terminating SSL with the let's encrypt certificate OR you can run pass through with RavenDB.  You cannot do both.  (see my other ticket, using Exec with OpenSSL against a cert-manager generated let's encrypt certificate results in an error using the openssl converted ket/crt into pfx.)

The fundamental problem is that RavenDb works fine in k8s if the only thing in your k8s cluster is RavenDb.  But that is NOT how anyone other than a service provider in a 0 trust environment would run it. I.e. it's perfectly fine for you with your cloud product. It is NOT fine for anyone using k8s as it's designed to run with ALL of your code and dependencies in the k8s cluster with a single point of entry through the ingress. I have yet to see ANY design of RavenDB running in k8s that doesn't defeat everything else running in the cluster.  i.e. If you require SSL pass through to RavenDb then you cannot run it in the same cluster as your website's nor API because either you're now terminating SSL at each of those and have to maintain certificates at every one of those endpoints instead of the single RP and just created an N^replica maintainence problem, or RavenDb won't work even if you using a self-signed certificate in RavenDb and have the RP reencrypt to RavenDb.

This is the fundamental problem statement. Show me a working configuration with a .NET API where the RP is doing SSL Termination, reencrypting to the .NET Api project using the .NET Api Project's self-signed cert that is trusted for everything in the cluster, and have the same work for RavenDb in the same cluster and do so automated without having to hack the hell out of it.

1. => It doesn't work. If it does work, demonstrate as such using the industry standard way in k8s of retrieving let's encrypt certificates which is jetpack/cert-manager.

2. As I've said, feel free to give me an example using a self-signed cert on RavenDb itself or even signed using the cert-manager certificate with the RP not set to ssl pass through thus defeating everything else inside of the cluster if you think this is an issue.  And to be clear by mitigated, I mean, the default configuration of k8s doesn't allow the examples you gave to actually work. In every case their examples of so-called insecurity of what I've proposed required humans to run code explicitly insecure and there was absolutely no automated approach that could have gotten you there. Even your example of node opening consoles is useless, because the console within the container with the default security permissions of containers doesn't let that container escalate to root on the host cluster, and without explicitly using --privilaged or giving NET_CAP to the cluster, both of which require humans to configure it that way, NOTHING in any container will ever be able to snoop traffic.  So, I'm fine running certs, but client certs, which are nothing more than bearer tokens are not secure in and of themselves any more than login and passwords. There's literally no difference in any scenario. (which is why the banking industry is not allowed to use client certificates without login and password anymore and can only use them as a method of doing 2fa. I'm literally the guy that proved this to them and got the rules changed.)  While using a client cert might be a way to ensure traffic between services is authorized, it is no more secure than using hashed keys like Azure Storage or AWS or anyone else uses in any setup with the same transport security and any escalation of privileges achieved in the container also by definition exposes that client cert which is now a bearer token for blind trust. (exactly like Azure Storage keys, which is why they're going to RBAC and we don't store any of these anywhere anymore.)

3. Docker privileged: Every one of your examples of why using unencrypted wire communication within a k8s cluster was not secure required --privileged or NET_CAP privileges on the container. I was not claiming RavenDb required it. I was stating a fact that your assertion that it's a security risk to run containers communicating with each other in a k8s cluster without transport security is unfounded and would require a complete mis-configuration of your cluster and to do so actively. And if you did so, it wouldn't matter if you were using transport security and client certificates, because the same access required to use those exploits also would compromise the certificates.


So really what this is about is:

Please update your documentation to provide a real-world style implementation of k8s where:

1. RavenDb is within the cluster itself, and has no external communication other than RavenDb Studio. (you can feel free to encrypt the server and add client certificates however you wish, I don't care to argue on this one, the point is moot because the overhead is minimal and the RP can easily reencrypt using whatever Cert you want)
2. The cluster itself uses the industry standard jetpack/cert-manager (and by industry standard I mean the k8s documentation explicitly instructs its use) to terminate external SSL at the RP.
3. The RP does not have SSL-passthrough enabled.
4. The language of your choice hello-world REST api running within the cluster, with SSL termination at the RP, using a self-signed cert if you insist, where the RP recrypts to the REST API. This REST API will communicate directly with the RavenDb cluster within k8s.
5. The ability to use Raven Studio externally or through some other method to the cluster that doesn't require me to stand on my head externally and still securely. (i.e. I want to run RavenDb as a black box most of the time, but I should still be able to get in and manage it visually when problems arise).
6. At no point do I have to configure multiple containers within the k8s cluster certificates more than once with certificates, nor intervene nor maintain multiple let's encrypt methods in multiple containers.



(and seriously, client certificates alone are not secure. They're bearer tokens. Compromise of the certificate and you're done. For end users with things like Raven Studio, they should always be used as 2fa with login and password at worst.  And having the transport certificate and the default client certificate in the same cert is very not good, they should have nothing to do with each other.)

**Comment by JohnGalt1717** [comment]
I've enabled this: https://github.com/ravendb/ravendb/blob/v5.0/src/Raven.Server/Config/Categories/CoreConfiguration.cs#L27

However, because the cert is for a public address and not the internal url, it rejects it for setting up the cluster.  Similarily trying the ip also fails with the same issue.

So once again stymied, although I have a single database setup through massive effort on a single node within k8s with it actually working and not defeating everything else in the cluster... So if I can get around the cn/san not matching (which is inmaterial in the case of the cluster) then I can at least hack this using k8s port forwarding to make studio work for the moment.

**Comment by ayende** [comment]
From the other ticket, you are now able to setup openssl correctly to read the certs from `cert-manager`, right?
So there shouldn't be an issue with running passthrough with the `cert-manager`.

I'm not sure that I follow what the issue is with regards to N^replicas? 
The clients needs to have a client certificate that RavenDB will trust, yes, but I fail to see how this relates to running your application inside the same cluster?

Note that I would be very doubleful that you _can_ get a Reverse Proxy to sit in front of RavenDB. You'll need to make it handle client cert auth, and they are generally not meant to do that.

There are a few ways to make this work for your scenario:

* Register the client certficates for the apps you are using in RavenDB. Note that the client certificate doesn't have to relate to the server certificate in any manner.
* You can (but probably shouldn't) register a Well Known Certificate as part of the RavenDB configuration. 

You won't have a scenario with SSL Termination and Reverse Proxy, we explicitly don't want to support this, for the reasons outline above.

2) Your logic is similar to: If you'll just `free()` any memory you `malloc()` there will be no memory issues.
There is a _wide_ body of experience that shows that this isn't the case. And if your security configuration relies on there being no mistakes, it will fail.

In the case I outlined, you'll need a multi stage attack. First, get to the point where you have a way to execute code. The node example spawning console is a good example of how that can happen in a "trusted" environment. 
The next stage is to escape the container's limits. Here is how you can do that:
https://sysdig.com/blog/cve-2020-14386-falco/

"..enables an unprivileged local process to gain root access to the system."

3) RavenDB security properties shouldn't depend on the user not running anything with NET_CAP. I won't argue about "a complete mis-configuration of your cluster", the issue isn't that this is what it takes. The issue is that this happens _all the time_. 

For example: https://www.shodan.io/search?query=elastic

Took me 1 minute to find a database open to the world with no password that had real live data in it.


1) The RavenDB Studio is simply a web client on top of the existing REST API. There is no meaning to "allow only RavenDB Studio" with no external access.

For the rest, your requests contradict our threat model and security policies and cannot be acoomodated.

**Comment by JohnGalt1717** [comment]
No. I can't use cert-manager because you're checking the SN and not SANs. As a result, I can't issue a cert with cert-manager that has both our public wildcard dns, and the alternative internal dns names in k8's dns thus one server can't talk to the others in the cluster nor can I use kubectl port-forward to get into the raven statefulset directly and bypass the RP as this doesn't work either for the same reason AND allow unsecured can't be turned on and work with kubectl port-forward thus thwarting all efforts to find a work around for your refusal to support RPs properly.

My point to this whole thing is that your understanding of how a k8s cluster works is wrong. I would NEVER expose RavenDb outside the cluster directly. NEVER. And your requirements would mean that even if I did so, ALL other services within the cluster would either have to use client certificates (not happening on a public website that's in the same cluster!) or do their own SSL termination on each of those services. (not happening because that creates a logistical nightmare that will almost certainly result in embarrassment and service downtime because of an accidently expired certificate somewhere to say nothing of the heightened risk that someone makes a mistake in configuration or code and creates a security vulnerability)

Your example (again) requires a malicious user or bad configuration. Read carefully. AND in your scenario and your documentation example, that pod would then also have access to your transport and client base certificate, so your point is moot. (i.e. it can easily run kubectl get secrets and pull the secret you've got mounted or simply access them from the mount in the pod and then can run roughshod over the whole thing. In fact, mounting the certificate makes it far easier to hack because any code you run has access to the entire chain including client cert, without even breaking out of the pod.)

AND I already gave you the solution that would work even if I accepted your argument: Simply have the RP recrypt the communication using the RavenDB server's self-signed cert and communicate with the server over TLS. Then there is absolutely no benefit to a client certificate (bearer token) versus login and password (also a bearer token) in an end to end TLS environment even with an RP recrypting.  (and what I'm saying is directly from the OpenIDConnect website that goes through this in deepth with the 4 flows and why password credential and client certificate are effectively the same thing versus hybred or code flow which is vastly superior even without 2fa.)

**So since you're unwilling to recognize this, all I ask is that you provide some mechanism for this to work in the cluster, encrypted with a private certificate, all nodes in the raven cluster working properly on the k8s dns with each other, and me being able to access raven studio and the database over kubectl port-forward WITHOUT ANY ACCESS AT ALL OVER THE RP INGRESS.**

And do so in a way that doesn't require me to stand on my head to get certificates working.

I.e.: (to crush the 3 other stories when I thought this was going to be simple)

1. Allow issuance of a transport (server) self-signed certificate that is separate from the client certificate and provide explicit openssl commands to generate said certificate in a way that you find acceptable in documentation without an obviscation in multiple files. I've wasted over 8 hours of my life just screwing with your specific certificate requirements because you're using a single certificate for both transport and client validation which should never happen.
2. Recognize both the SN and SANs in said certificate and accept them. i.e. *.statefulsetname.k8s.cloud.net is the SN, ravendb, ravendb-0, ravendb-1, ravendb-2 (etc), are all SANs on the certificate which should also be accepted as should direct IP address access with the same certificate. (the later because of kubectl port-forward)
3. Allow me to separately issue the initial client certificate, or MUCH better yet, allow no client certificate on first run and have it either automatically dump the default client certificate into a directory on first run, or have the setup wizard generate the first one on first run and download from Studio, without requiring it initially and then lock the server down after the cert is generated and require the client cert there after. (on the dump to directory option, feel free to refuse access at all until the client certificate is removed from the directory it was dumped to)
4. Ensure that kubectl port-forward to the stateset works properly without obstruction.

This allows all of my services in k8s to access ravendb, separates the client certs from the transport cert making RavenDb more secure and making it less of a PITA to provision a new environment, and allows developers and support people to access the cluster when diagnosing issues directly if they have access to the cluster using kubectl and port-forward without exposing it over the RP and without requiring the RP handle client certificates that as you correctly noted isn't going to happen.

By doing so, I can viably keep RavenDb private in the k8s cluster, follow what you perceive to be an issue and make this work. Until I can make this work in at least this way, RavenDb is broken in how k8s is supposed to be used and will have to be dropped from the 3 major projects that I have it accepted for that combined would generate over $60k in revenue for you per year. (one of which is already spending money in your cloud for our test environment which is what this was all about in the first place, moving the test environment into a developer license in K8s, saving us some money during development, and then using that to replicate production when we're ready inside our production k8s)

Please provide a scenario where this will work, or a commitment to make this work at least, or tell me no once and for all so that I can cut bait and move on.

**Comment by ayende** [comment]
We are absolutely checking the subject alternative names for the certs.
You can also set things up so that the cluster will have multiple topologies (private / public / external).

The moment you want to access the Studio from outside K8s, which is very reasonable thing to want to do, you are exposing RavenDB. The Studio uses the same REST interface as the API, so there is no separation between the two. 

I fail to see what your reasoning to avoid using SSL inside the cluster. It adds a minimal amount of overhead and has very little operational cost. Your clients can pull the certificate from the secrets manager if needed, which eliminate the issue of updates.

If you security setup assumes no malciousness and 100% no faulty configuration, that is going to fail. 
Regardless, the issue is that you have is with authentication. You need to authenticate that the client is authorized to access a certain database. In your mode, all clients can access everything, which is not typical. You'll have different applications that can only access certain portions of the data. 
Putting it all behind a proxy defeats that.

1) We are using single certificate for ease of deployment, but there is no such requirement. 
The setup wizard will typically generate a separate client certificate for you.

2) SAN & SN are all acceptable in the cert. As for IPs, if your trusted certificate has that in the SAN, it should just work.

3) That is how the setup wizard works, see: https://ayende.com/blog/180801/ravendb-setup-a-secured-cluster-in-10-minutes-or-less

I think that this is getting a bit out of hand to handle via text here. I suggest we handle this via a call. You can ping us at support@ravendb.net with your timezone and we'll setup a call.
