### ISSUE TITLE
Information leakage via RouteNotFoundException

### ISSUE THREAD

**Issue by dbalikhin** [ravendb/ravendb#11586]
Visit any non-existing page after installation, e.g. /idontexist or go to live-test.ravendb.net/idontexist

Url | "/idontexist"
Type | "Raven.Client.Exceptions.Routing.RouteNotFoundException"
Message | "There is no handler for path: GET /idontexist"
Error | "Raven.Client.Exceptions.Routing.RouteNotFoundException: There is no handler for path: GET /idontexist\n   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-Stable-5.1\\51010\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 196\n   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-5.1\\51010\\src\\Raven.Server\\RavenServerStartup.cs:line 242"

Exact version is shown for unauthenticated user.

Is it by design or can be configured somehow?
I have a local instance and it behaves the same. Ideally, I want to see generic error, e.g. 404 Not Found.

**Comment by ayende** [comment]
Yes, this is by design. You can also get this in a more official manner using:

http://live-test.ravendb.net/build/version

In this case, this is an authenticated endpoint, but the: http://live-test.ravendb.net/setup/alive endpoint is an unauthencated one and it also expose the version (via a header).

Unauthenticated users can always get the version of RavenDB even without that, since they can use the studio endpoint and look at what version they get from the client code.

Note that this is needed because we want to give you a good error message when you fail auth.

**Comment by dbalikhin** [comment]
Thanks, I would prefer to have it configurable :)
Not a big deal for private networks though, just when you have a server with authentication in a public zone.

**Comment by ayende** [comment]
The problem is that trying to hide this information if more or less futile. We would leak that in many other manners.
The Studio ZIP file contents, the available endpoints (which you can enumerate and check what the error is, etc).

We would consider this information public if the server is accessible and assume that there is no additional risk in making this information easily accessible. Note that this doesn't impact the security properties.
