### ISSUE TITLE
IAsyncDocumentSession..Advanced.ExistsAsync() returns false if IDocumentStore.OnBeforeDelete throws an exception

### ISSUE THREAD

**Issue by AKlaus** [ravendb/ravendb#12398]
**Steps to reproduce:**
1. Setup throwing an exception in `IDocumentStore.OnBeforeDelete`, e.g. `store.OnBeforeDelete += (_, _) => throw new Exception();`
2. Attempt to delete an existing record, e.g. by calling `DbSession.Delete("Tickets/1-A")`
3. The record in the DB remains untouched thanks to the exception in the `OnBeforeDelete`
4. However, `await DbSession.Advanced.ExistsAsync("Tickets/1-A")`would return `false`.
5. Though, if call `DbSession.Advanced.Clear()` first then `ExistsAsync` would return `true`.

See a [relevant test in the YABT project](https://github.com/ravendb/samples-yabt/blob/7320c0e2f09035555b233fef2b0e967c63bad280/tests/Database.Tests/MultiTenancy/MultiTenancy_Delete_Tests.cs#L60).

**Comment by ayende** [comment]
*Any* exception that is thrown by the session would effectively invalidate it, note.
What actually happens here is that we first record that we intend to remove the document, even though the exception "failed" the operation. At this point, you cannot assume anything about the state of the session.

To do otherwise would cause us to have to be very careful and would still leave you with complicated scenarios in the case of server side failure. 

`ExistsAsync` checks first that the document was registered for removal, and it wasn't removed when the exception happened.
