### ISSUE TITLE
Unique and TTL Indexes

### ISSUE THREAD

**Issue by CyberCyclone** [ravendb/ravendb#13335]
Hi,

I've tried finding info on creating a Unique Index and also an index that has a TTL but I can't find anything on either of them.

I can understand that a Unique index doesn't really make sense as indexes are "eventually consistent", so there's a chance that there would be conflicts. It's reasonably easy to move the unique fields data into the Id field, but a TTL on an index I thought would make be possible.

I'm trying to avoid creating a `setInterval` that checks the DB for old docs and remove them.

Can you please let me know if either is possible?

Thanks!

**Comment by ayende** [comment]
RavenDB has directly support for document expiry, you can use that instead of doing manual work via TTL indexes.
See the feature here: https://ravendb.net/docs/article-page/5.3/python/server/extensions/expiration

As for unique constraints, they are supported as well, but not using an index.
See here:
https://ravendb.net/articles/ravendb-5-2-simplifying-atomic-cluster-wide-transactions

**Comment by CyberCyclone** [comment]
Awesome, thanks for that @ayende!
