### ISSUE TITLE
Index cannot be used for 'more like this' after related document changes 

### ISSUE THREAD

**Issue by Ron-Brouwer** [ravendb/ravendb#14078]
Hi Guys,

We just encountered some very strange behavior in serverside indexing while tracking more than one collection. If seems that in some cases you will corrupt indexes on the server without warning. We created a unit test with a simple loaddocument to demonstrate the issue, but we see the same issue when using a MultiMap index. It happens as soon as there are multiple collection tracked and an update occours in the tracked collection. After that, morelikethis is broken.. We have no further ideas as to why this happens. Hopefully the impact is minimal, but this should be investigated.

**Failing unit test:**

```
public class MoreLikeThisWithReferencedCollectionTest : RavenTestDriver
    {
        [Fact]
        public void MoreLikeThisShouldReturnSameResultAfterTrackedCollectionChanges()
        {
            using (var store = GetDocumentStore())
            {
                store.ExecuteIndex(new Person_ForSearch());

                var firstRegionId = "";
                var secondRegionId = "";
                var firstPersonJson = "";

                using (var session = store.OpenSession())
                {
                    var firstRegion = new Region()
                    {
                        Name = "Europe"
                    };

                    var secondRegion = new Region()
                    {
                        Name = "Asia"
                    };

                    session.Store(firstRegion);
                    session.Store(secondRegion);

                    firstRegionId = session.Advanced.GetDocumentId(firstRegion);
                    secondRegionId = session.Advanced.GetDocumentId(secondRegion);

                    var firstPerson = new Person()
                    {
                        FirstName = "Gert",
                        RegionId = firstRegionId
                    };

                    var secondPerson = new Person()
                    {
                        FirstName = "Gert",
                        RegionId = firstRegionId
                    };

                    var thirdPerson = new Person()
                    {
                        FirstName = "Gert",
                        RegionId = secondRegionId
                    };

                    firstPersonJson = JsonConvert.SerializeObject(firstPerson,
                           new JsonSerializerSettings()
                           {
                               NullValueHandling = NullValueHandling.Ignore,
                               DefaultValueHandling = DefaultValueHandling.Ignore,
                           });

                    session.Store(firstPerson);
                    session.Store(secondPerson);
                    session.Store(thirdPerson);

                    session.SaveChanges();
                }

                WaitForIndexing(store);

                // Get the amount of morelikethis items.
                var originalResults = CountExecuteMoreLikeThis(firstPersonJson, store);

                // Update a region so the index needs to be updated.
                using (var session = store.OpenSession())
                {
                    var region = session.Load<Region>(firstRegionId);
                    region.Changed = true;

                    session.Store(region);
                    session.SaveChanges();
                }

                // Wait for the index to be updateds
                WaitForIndexing(store);

                // Check if we get the same amount of items
                var secondResults = CountExecuteMoreLikeThis(firstPersonJson, store);

                // Both should return 3 items
                Assert.Equal(3, originalResults);
                Assert.Equal(3, secondResults);
            }
        }

        private int CountExecuteMoreLikeThis(string person, IDocumentStore store)
        {
            using (var session = store.OpenSession())
            {
                var results = session.Advanced.DocumentQuery<Person_ForSearch.Result, Person_ForSearch>()
                    .MoreLikeThis(builder => builder
                        .UsingDocument(person)
                        .WithOptions(new MoreLikeThisOptions()
                        {
                            MaximumQueryTerms = int.MaxValue,
                            MinimumDocumentFrequency = 0,
                            MaximumDocumentFrequencyPercentage = 100,
                            MinimumTermFrequency = 0,
                            MinimumWordLength = 0,
                        })
                    ).Take(100)
                    .SelectFields<Person>()
                    .ToList();

                return results.Count();
            }
        }

        public class Person_ForSearch : AbstractIndexCreationTask<Person, Person_ForSearch.Result>
        {
            public class Result : Person
            {
                public string RegionName { get; set; }
            }

            public Person_ForSearch()
            {
                Map = people => from person in people
                                let region = LoadDocument<Region>(person.RegionId)

                                select new Result
                                {
                                    FirstName = person.FirstName,
                                    RegionName = region.Name
                                };

                Index(t => t.FirstName, FieldIndexing.Exact);
                Index(t => t.RegionName, FieldIndexing.Exact);
                StoreAllFields(FieldStorage.Yes);
            }
        }

        public class Person
        {
            public string FirstName { get; set; }

            public string RegionId { get; set; }
        }

        public class Region
        {
            public string Name { get; set; }
            public bool Changed { get; set; }
        }
    }

```

Thanks in Advance.

Ron Brouwer

**Comment by maciejaszyk** [comment]
Hi Ron,
Thanks a lot for the feedback and the test!

I've investigated it. I found out it is an issue related to the search engine `Lucene` and its internal processing of the MoreLikeThis feature.
I've looked into your test and found out you're setting this:
`MaximumDocumentFrequencyPercentage = 100,`

If you delete it, everything will work as it is supposed because the setting by default is null, which means unlimited / all docs.

**Comment by Ron-Brouwer** [comment]
Hi Maciej,

Thanks for a solution! Are you sure the underlying issue won't impact anything else?

**Comment by maciejaszyk** [comment]
I think this is not the issue but rather how this feature works in the backend.

Can you tell me what you expect from these parameters?

**Comment by Ron-Brouwer** [comment]
It's more that I would like to understand why the same parameters can yield different results. What changed in the index that causes the different results.

**Comment by arekpalinski** [comment]
We'd need to talk about the implementation details of how Lucene works under the covers. It's pretty wide and tough topic. Let me try to briefly explain what happened in your case. In general, updates to indexes make that new segments might be created. If that's a new entry it's just added. If we deal with an update then we have to delete old entries before inserting new ones. That is marked at segment level and makes and old entries aren't searchable. 

This means that it's possible to have "duplicated" terms in segments - but some of them are effectively deleted so we don't see them in query results. The implementation of more like this feature looks for terms in the segments. When Lucene returns the total number of entries containing that term, it counts even the deleted ones - that is quite surprising.

In your case the index had 3 entries (documents) but 5 terms for FirstName field (the region doc update made that old two entries were deleted and inserted again - because this doc was referenced by two person docs in the index def) . The limit that you put - `MaximumDocumentFrequencyPercentage` made that it was filtered out from the more like this query results because we had 3 entries in total but 5 terms "Gert" in all segments. 

I agree it's not very intuitive but it involves the internal implementation of Lucene search engine. We'll try to have a deeper look into this next week.

**Comment by Ron-Brouwer** [comment]
It makes sense now. Thanks for your detailed explanation!

**Comment by ayende** [comment]
To give more context, that is how it is _meant_ to work. There isn't a bug here.
The value you set is meant to: `Ignore words which occur in more than this percentage of documents.`

For example, when you are `MoreLikeThis` on the RavenDB docs site, you'll want to exclude very common terms such as `RavenDB` or `database`. 

The manner in which Lucene actually manage the terms internally means that it is common for terms on updated documents to remains valid for a certain duration of time after they were updated.
In other works, you changed your name from `Ron` to `Brouwer`, and that will update. But the list of "first names" will have the term `ron` in it for some time (even if there are no matching documents for that, since the document was deleted).

When you use `MoreLikeThis`, the code there is operating on the level of the terms. Since some terms belong to deleted documents as well, that push them to over 100%, which evicts them.

This is a bit complex, but there isn't a bug here. Setting the value to 100% is probably not something that you want to do, though.

**Comment by Ron-Brouwer** [comment]
Thanks Oren!

Thats what I understood from the previous message. I have (some) knowledge of Lucenes internal workings. My team and I did not interpretate this setting correctly and expected the same result. Perhaps a warning within the docs and/or code could help other people from making similar misstakes? Default behavior would be a nice thing to mention in code and prevent people from wanting to change this setting to 100% just to be sure all documents are considered. I know, stupid devs ;)
