### ISSUE TITLE
macOS Ventura and M1 Mac installation issues

### ISSUE THREAD

**Issue by dylans** [ravendb/ravendb#15170]
Trying to get RavenDB 5.4.4 running on the new macOS Venture on an M1 Mac (not inside a Docker container or a VM) and I'm running into a few issues:

* Need to disable GateKeeper to get past a wall of dialog warnings (might be fixed by installing .Net Core first)
* run.sh is failing on this line, `eval "./$EXECUTABLE --browser";`   

```
> ./run.sh
./run.sh: line 30: 44843 Killed: 9               ./Raven.Server --browser
```
Tried removing --browser, process still gets killed.

I've tried .Net core 6.x and 7.0RC for Mac ARM64

**Comment by garayx** [comment]
Thanks for reporting this, we will look in to the issue asap.

https://issues.hibernatingrhinos.com/issue/RavenDB-19479/Cannot-run-ravendb-on-macos-m1

**Comment by ayende** [comment]
Question, what exact version are you running?
If you are running this manually, what do you get? What is the exit code / sys log statements?

**Comment by dylans** [comment]
5.4.4 macOS ARM
macOS 13.0 (Ventura)

```
$ ./run.sh
./run.sh: line 30: 73599 Killed: 9               ./Raven.Server --browser
$ sudo ./enable-debugging.sh
Enabling debugging for RavenDB...
NOTE: Please make sure appropriate glibc is installed on your OS.
Add mscordaccore.so to ldconfig.../Users/default/livingspec/RavenDB/Server/libmscordaccore.so file does not exist. Exiting...
$ brew install glibc
glibc: Linux is required for this software.
linux-headers@5.15: Linux is required for this software.
Error: glibc: Unsatisfied requirements failed this build.
```

**Comment by ppekrol** [comment]
Hi,

I've managed to run 5.4.4 on macOS 13.0, but due to lack of notarization (we are working on that) it required few additional steps:
1. https://issues.hibernatingrhinos.com/issue/RavenDB-18889/MacOS-binaries-must-be-signed-otherwise-process-is-killed#Workaround-for-the-time-being
2. in Privacy & Security had to allow applications from App Store and identified developers
3. When ./Raven.Server was executed, a lot of messages with *.dylib showed and had to authorize the execution also from the Privacy & Security window (Security subsection)

I hope that this helps.

**Comment by dylans** [comment]
the codesign trick got me over the hump... The number of "approve anyway" files seems to have grown a lot since Monterey.

Can leave it open or close it at your discretion, but having a version that doesn't require approval for each file would be a huge win! 🤞

**Comment by ppekrol** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-14528/Look-into-MacOS-notarization
