### ISSUE TITLE
how to check if raven studio is already opened?

### ISSUE THREAD

**Issue by antontuz** [ravendb/ravendb#15925]
I have following code:
```
protected override async Task OnInitializing()
    {
        await WaitUntilConnected();

        await ConfigurationEmit( _configuration );

        _documentStore = await StartServer();

        if ( Debugger.IsAttached )
            EmbeddedServer.Instance.OpenStudioInBrowser();

        IndexCreation.CreateIndexes( Assembly.GetExecutingAssembly(), _documentStore );

        await InitializeSubscriptions();
        await InitializeCommandHandlers();
    }
```
The problem is here: `EmbeddedServer.Instance.OpenStudioInBrowser();`

I run server and service opens raven studio. I can stop server and run it again. Raven will open studio again
So how to avoid this?
I don't want to open the same studio twice

**Comment by ppekrol** [comment]
hi @INTERNALINTERFERENCE 

The `OpenStudioInBrowser` is a very simple piece of code that just orchestrates OS to open a link (via default browser). The idea here was to only use it when needed and remove it afterwards.

Code: https://github.com/ravendb/ravendb/blob/b1b323d777173fcfdc0753de6fbd02054230cdbf/src/Raven.Embedded/EmbeddedServer.cs#L327-L345

In order to accomplish what you are asking for, you would have to detect what browser processes are running, connect to them via their API and check if one of the tabs is opened with the requested URL. This is not sth that we are planning to do in nearest future, so you would have to handle it yourself.  Not sure if there is any other way to accomplish this.
