### ISSUE TITLE
Question: Topology change and replication error

### ISSUE THREAD

**Issue by JezhikLaas** [ravendb/ravendb#17833]
Hello,
In our 3 node production cluster a replication error can be observed one or two times a day and topology update messages like "Node C was recovered from rehabilitation and promoted back to member" pop up a few times a day. Is this expected or something to be worried about?

Raven Version is 5.4.112, the instances are running in docker containers on Linux.

**Comment by ayende** [comment]
That can happen when there is a transitory disruption in the network. For example, if you are rebooting the instance or the host.

The cluster detects that and take steps to ensure that everything is fine, and let you know about that in case you care to investigate what caused this. It's advisable to understand what could cause this, yes. Primarily because if this is something that you cannot figure out the cause for, it can happen in the future.

But the cluster itself is ready to handle that without any disruption to your applications and systems

**Comment by JezhikLaas** [comment]
Yes, I can confirm that the cluster handles this gracefully. It stays responsive and continues to work w/o any problems from the application services view.  Thanks for the answer, I think, we will have some talks with the networking / hardware guys from tomorrow on.
