### ISSUE TITLE
Security Vulnerabilities in transitive assemblies

### ISSUE THREAD

**Issue by jmajoor** [ravendb/ravendb#18615]
You have a dependency on `NCrontab.Advanced`, which was written for .NET Frameworks and .NET Standard 1.0.
Due to this dependency your `Raven.Server.deps.json` has lots of transitive dependencies on very old .NET standard assemblies.

This then produces vulnerability alerts with security scanners that are using the `deps.json` files for their scans.

I understand that these particular vulnerabilities in transitive assemblies are in fact false-positive reports, but unfortunately popular security scanning tools such as `Trivy` keep reporting them.

The crontab package you use, doesn't seem to be maintained.
Would it be possible to find an alternative for this dependency so RavenDB won't trip up security scanners.

**Comment by ppekrol** [comment]
hi @jmajoor 

Thank you for your feedback.

We are constantly monitoring our direct and transitive dependencies. Actually to be sure we are on the safe side, we are using 3 separate tools for this. The issue is that all of those tools are not taking into account what assembly is actually used when you run the application e.g. I'm pretty sure that one of the dependencies of that `NCrontab.Advanced` is `System.Security.Cryptography.X509Certificates` with version 4.3.0. We actually got a report from one of our tools that version 4.1.0 is used in RavenDB Server, but the Q is if this is the case?

The answer is here:
![image](https://github.com/ravendb/ravendb/assets/446555/4cfbffcb-846c-4317-9a76-fbcd85223b54)

As you can see the assembly that actually was loaded is 8.0.0 one (resolved from runtime version), not 4.3.0 or 4.1.0. As I wrote, those tools are doing their best, but they perform static analysis of the `deps.json`.

**Comment by ppekrol** [comment]
I've created https://github.com/ravendb/ravendb/pull/18623 which removes those vulnerabilities from the list, although this is actually a workaround for the tool.

**Comment by jmajoor** [comment]
Thanks for looking into this. I am aware that these are actually issues with the scanning tools and `Trivy` has known about this issue for over a year and claims it is a Microsoft defect and not their misunderstanding of transitive dependencies.  Some other tools, that have the same issue, are working on fixing that (as we reported this issue with the tool as well). 
Your fix will allow us to avoid us from having to go through an exemption process (which may no always be successful, due to lack of knowledge on this subject).

**Comment by ppekrol** [comment]
I hope it will be fine after merging this. The `dotnet list package --vulnerable --include-transitive` yields 0 vulnerabilities in this PR. 

I'm wondering as well if this is a tool issue or underneath those tools are actually using above command which also has issues with detecting that. For system assemblies MS does a lot of magic and at the end even if you reference one version, you are ending up with a runtime one at the end.

**Comment by jmajoor** [comment]
Should this have been included in 6.0.104?
Unfortunately I still see:
System.Net.Http 4.1.0
System.Security.Cryptography.X509Certificates 4.1.0

**Comment by ppekrol** [comment]
Hi @jmajoor 

We merged the PR, but it was not part of the 104 release. The next 6.0 will have those adjustments.

**Comment by jmajoor** [comment]
Verified the latest release, and it all looks good now. Thanks.
Also `trivy` will release an update soon to address these false positives, so hopefully this is a thing of the past.

**Comment by ppekrol** [comment]
Great, thanks for update!
