### ISSUE TITLE
`Where(x => x.SomeCollection.Any())` maps to `exists(SomeCollection)`, which can have bad performance compared to `SomeCollection.Count > 0`

### ISSUE THREAD

**Issue by danielwinkler** [ravendb/ravendb#18700]
See discussion

https://github.com/ravendb/ravendb/discussions/18698

We are creating the query with LINQ like

```
        var collectionBeforePaging = session
            .Query<Assignment>()
            .Where(a => a.StudentId == studentId)
            .Where(x => x.Trainings.Any())
         ;
```

which creates `exists(SomeCollection)`

If we write 

```
        var collectionBeforePaging = session
            .Query<Assignment>()
            .Where(a => a.StudentId == studentId)
            .Where(x => x.Trainings.Count > 0)
         ;
```

we get a `SomeCollection.Count > 0`, which is preferable as explained in the linked discussion.

**Comment by Lwiel** [comment]
Please note that you are using a dynamic query (without specifying a static index). It means that an auto index will be created under the covers to handle the query. The query itself affects the definition of an auto index, more specifically it defines what fields will be indexed. 

Using `exists(SomeCollection)` will instruct an auto index to index `SomeCollection` field (since it's a collection it will be indexed as JSON array), while `SomeCollection.Count > 0` will index only lengths of arrays. 

For example, query `from "Orders" where exists(Lines)` executed on sample data creates an auto index with separate term for each document.
![Screenshot 2024-07-01 161616](https://github.com/ravendb/ravendb/assets/32438625/8edb7b68-3df9-4eac-b049-149746d58768)

Query `from "Orders" where Lines.Length > 0` executed on sample data creates an auto index with much less terms than the previous index.
![Screenshot 2024-07-01 162613](https://github.com/ravendb/ravendb/assets/32438625/c9b8271c-ede7-473a-869a-706df0790336)

As you already mentioned in linked discussion, creating static index to index the length of the field is a good idea.

Server-side rewriting the first query would be problematic because it requires the `SomeCollection.Length` to be already indexed in the index used for query. In case of static indexes and auto indexes created before such change it could be not indexed.

**Comment by danielwinkler** [comment]
Thank you for the detailed explanation @Lwiel ,

I thought more of doing the rewriting on the client side.

So in the linq provider, the expression for a non empty collection (`.Any()`) could be translated to a `count > 0` query instead of the `exists` query. Then the planner for the auto index would already know how and what to index.

But I may have a wrong understanding of the inner workings.

**Comment by Lwiel** [comment]
The client-side rewriting of such query would be a breaking change for existing auto indexes. Even if we decided to go this way it would introduce fields inconsistency into auto-indexing mechanism, hence increasing its complexity. 

Instead of doing it automatically we recommend to explicitly manage it when defining a query or to use static indexes to control what is actually indexed.

**Comment by danielwinkler** [comment]
I see, thank you for the explanation and recommendation.

All the best,
daniel
