### ISSUE TITLE
Feature idea: Use 2FA only for write/admin access

### ISSUE THREAD

**Issue by stevehansen** [ravendb/ravendb#18827]
I think it would be useful to have a client certificate that has read-only access, and that you can use the 2FA feature to elevate the session to write/admin access. This makes it easy to see/lookup data without the danger of accidently changing anything, if something does need to change you can quickly use the 2FA token to upgrade your session for a small period.

**Comment by ayende** [comment]
We already have both features independently. Read-only access and 2FA verified access.

The problem is that the scenario you are describing is _not_ a security feature, but you are trying to look at it as such.

Given a certificate that has read-only access & 2FA - you are trying to protect from mistakes (not maliciousness), I assume.
The problem is that the _point_ of 2FA is that you need the second factor.

If you have the certificate installed on your laptop, and you lost that. Someone have "just" read access to your database is _pretty_ bad.

The feature also suffers from another problem. You are granted an untrusted source (Since you don't have 2FA) access, now they can do a much deeper scan / attempts to circumvent your security controls.

**Comment by stevehansen** [comment]
@ayende thanks for the insights on this, I might have given the wrong impression, it was not meant as a security feature

The biggest issue currently is that is is hard to switch client certificates inside the browser, I could use node A with a read-only certificate and node B with a write/admin certificate but that is waiting for something to go wrong and sometimes I don't have the same databases on each node.

Maybe it doesn't need to be linked to the 2FA feature perse but I was more thinking in lines of a UAC prompt/sudo, my user has admin access, but I don't always want to be in full admin mode.

I don't expect a fix/change, we can definitely work with the current tools, just throwing out the idea in case someone has similar thoughts/ideas.

**Comment by ayende** [comment]
A long time ago, there was `window.crypto.logout()` which would allow us to refresh which client certificate is used.
That is no longer supported (10+ years).

I'm not sure but _maybe_ a request to an endpoint that would reject the client certificate may cause it to refresh the certificate.
That information too, is pretty old: https://stackoverflow.com/a/10273994/6366

**Comment by stevehansen** [comment]
It seems at least Edge provides some UI for it: https://stackoverflow.com/a/78093429/295296

4 clicks and it allows me to pick a different certificate, without restarting the whole browser, I think this setup would be enough for me, the alternative will probably be more complex that what it solves

Thanks for the suggestion, for me this can be closed
