### ISSUE TITLE
RavenDB v6+ introduced steady growth of memory consumption over time

### ISSUE THREAD

**Issue by alex-bermishev** [ravendb/ravendb#19342]
after upgrading to RavenDB v6 (and to v6.2 recently) we noticed engine's much grown memory appetite, compared with v5.4

we collect some metrics on our development test benches.
we do periodically write data into RavenDB instances at 3/min rate. each document is about 2-3kb.

v5.4
![photo_2024-04-25_09-56-31](https://github.com/user-attachments/assets/de98d653-0061-438b-a382-34d394080410)
![photo_2024-04-27_09-39-02](https://github.com/user-attachments/assets/b6c0b173-c9c1-45f9-9254-cc5af7f5af8c)
![photo_2024-09-27_12-05-19](https://github.com/user-attachments/assets/774993de-3555-4108-9b56-b3f7e027a379)

v6+
![photo_2024-08-30_09-57-23](https://github.com/user-attachments/assets/c3105c2b-b229-4017-b674-0899ce56f416)
![photo_2024-09-02_11-35-23](https://github.com/user-attachments/assets/7b09c45e-cb16-41ae-9f6b-c4550a956f06)
![photo_2024-09-22_03-00-07](https://github.com/user-attachments/assets/b7823898-beab-45c2-96aa-1e3181b257f3)
![photo_2024-09-27_11-53-43](https://github.com/user-attachments/assets/e2e09a33-0f16-45fb-8168-1480a347d846)
![photo_2024-09-27_11-53-52](https://github.com/user-attachments/assets/fbb0d408-1ba0-46b7-832c-d2453b1739b4)

here is the metric of RavenDB process memory consumption over a long period of time.
observe noticeable increase after about 2024-06-13 (that's when we did upgrade v5.3 to v6.
![image_2024-09-19_19-42-28](https://github.com/user-attachments/assets/4c844216-821b-41ac-9784-e36d273193b5)

out project is supposed to be available 24/365, and we are concerned a bit, whether there is a memory leak in RavenDB v6?
will such a constant and steady memory consumption growth be a problem over lengthy period of uptime?

**Comment by ayende** [comment]
When you are looking at memory in RavenDB, there is a big detail missing. RavenDB will use as much memory as it can, and using more memory is _better_ (you get faster speed).

The issue is what kind of memory, see here for a full explanation:
https://ayende.com/blog/181729-C/understanding-memory-utilization-in-ravendb

In general - it looks like you are checking for `RSZ` which I'm assuming stands for Resident Set Size.
That is the amount of memory that RavenDB uses, which includes memory mapped file data. The OS can discard that memory whenever it is needed, but will use that until that point to speed things up.

Take a look at this endpoint for example:

http://live-test.ravendb.net/admin/debug/memory/stats

In particular, see:

```
    "MemoryInformation": {
        "PhysicalMemory": "1.886 GBytes",
        "WorkingSet": "733.84 MBytes",
        "ManagedAllocations": "197.77 MBytes",
        "UnmanagedAllocations": "6.08 MBytes",
        "LuceneManagedAllocationsForTermCache": "0 Bytes",
        "LuceneUnmanagedAllocationsForSorting": "0 Bytes",
        "EncryptionBuffersInUse": "0 Bytes",
        "EncryptionBuffersPool": "0 Bytes",
        "EncryptionLockedMemory": "0 Bytes",
        "MemoryMapped": "576 KBytes",
        "IsHighDirty": false,
        "DirtyMemory": "0 Bytes",
        "AvailableMemory": "90.72 MBytes",
        "AvailableMemoryForProcessing": "929.23 MBytes"
    },
```

See here:

```
        "WorkingSet": "733.84 MBytes",
        "ManagedAllocations": "197.77 MBytes",
        "UnmanagedAllocations": "6.08 MBytes",
```

Those are the most interesting bits for us. 
RavenDB is holding 730MB in memory, but only ~200MB is used internally, the rest is file cache.

**Comment by alex-bermishev** [comment]
so, there should be no problem, right? =)
obvious behaviour change of v6 compared to v5.4 really concerned us.

thanks for pointing significant metrics, we'll switch monitoring to that.
